name: flutter_clock
description: A Simple Flutter project to display World Clocks dynamically from WorldTimeAPI.
publish_to: "none"
version: 2.0.2+5

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  country_icons: ^2.0.2
  flappy_search_bar: ^1.7.2
  flutter_spinkit: ^5.0.0
  fuzzy: ^0.3.0
  google_fonts: ^2.1.0
  http: ^0.13.3
  intl: ^0.17.0
  octo_image: ^1.0.0+1
  provider: ^5.0.0
  shared_preferences: ^2.0.6
  transparent_image: ^2.0.0
  url_launcher: ^6.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "time_zone"
  image_path: "images/time_zone.png"

flutter:
  uses-material-design: true
  assets:
    - images/
    - assets/